### ISSUE TITLE
Vue Example

### ISSUE THREAD

**Issue by koca** [Prettyhtml/pretty-html-web#10]
Examples line 28:

https://github.com/Prettyhtml/pretty-html-web/blob/0d01fa550987c865e00acee77591973d34bb4b54/src/utils/Examples.js#L28

Did you forget to delete this or it should stay?
cc @StarpTech

**Comment by StarpTech** [comment]
It should stay but if you think it doesn't look good you can remove it. It added it because it shows a special case.
