### ISSUE TITLE
Show version of prettyhtml in the frontend

### ISSUE THREAD

**Issue by StarpTech** [Prettyhtml/pretty-html-web#2]

**Comment by koca** [comment]
yep I was thinking the same thing but where? below the logo or in the about section? :D

**Comment by StarpTech** [comment]
I would say above the "editor" label with light grey out font or like this:

![image](https://user-images.githubusercontent.com/1764424/46314869-086a8900-c5cc-11e8-87a8-2564e91fe750.png)

**Comment by StarpTech** [comment]
I added a basic version label beside the link in the help section for debugging purposes. Feel free to improve it.
