### ISSUE TITLE
Netlify build isn't triggered

### ISSUE THREAD

**Issue by StarpTech** [Prettyhtml/pretty-html-web#8]
I pushed a new build for 4 hours ago but there is no update. @koca can you check it?

**Comment by StarpTech** [comment]
Can you give me access as well?

**Comment by koca** [comment]
I see that build was failed.
here is the log:
```
12:36:43 PM: error Couldn't find match for "feature/" in "_c" 
for "https://github.com/StarpTech/property-information.git".
```
i don't have a team account so i can't give you access.
If you send a PR you can see the build log.

**Comment by StarpTech** [comment]
Are you able to fix it?

**Comment by koca** [comment]
Can you open your twitter DM maybe? where can i send you a message?

**Comment by koca** [comment]
It's failing because (i'm guessing) you've pushed `package-lock.json`. And i use yarn as a deps manager.

**Comment by StarpTech** [comment]
Yes, I also found it but why? NPM works!

**Comment by koca** [comment]
and i guess the problem is the `#` char in the branch name

**Comment by StarpTech** [comment]
You're right this so worst 😄

**Comment by koca** [comment]
we've just discovered a yarn issue :D

**Comment by StarpTech** [comment]
thanks for investigating 👍
