### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by StarpTech** [Prettyhtml/pretty-html-web#9]
How much effort does it take to provide a response design?

**Comment by koca** [comment]
I can do it but what's the use case?

**Comment by StarpTech** [comment]
Better first impression when people check it out via smartphone or tablet.

**Comment by koca** [comment]
Got it don't havenl time this week. But Next week can be. Ok?

**Comment by StarpTech** [comment]
Sure, that would be awesome.

**Comment by koca** [comment]
Hey! so here is the prototype for the mobile version and it will be more or less the same for tablet version.

thoughts? 🤔 
![mobile](https://user-images.githubusercontent.com/342666/48146077-480c4b00-e2c5-11e8-8fad-f78c943321d1.png)

**Comment by koca** [comment]
@StarpTech Mockup 😃 
![mockup](https://user-images.githubusercontent.com/342666/48146252-9c172f80-e2c5-11e8-95eb-f4fa0fc6fcdb.png)

**Comment by StarpTech** [comment]
![m1nep7h](https://user-images.githubusercontent.com/1764424/48146378-1ee3be80-e2b5-11e8-98fb-cdbc8442d60b.gif)

**Comment by StarpTech** [comment]
Is the example list extendable? Can I scroll the right?

**Comment by koca** [comment]
yep.

**Comment by StarpTech** [comment]
What's your status?
